"""add_iep_ai_draft_model

Revision ID: 8b9997513ebc
Revises: f35fa30eba82
Create Date: 2026-03-26 15:47:21.390190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9997513ebc'
down_revision: Union[str, Sequence[str], None] = 'f35fa30eba82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iep_ai_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_log_id', sa.Integer(), nullable=False),
    sa.Column('draft_content', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_log_id'], ['iep_communication_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iep_ai_drafts_child_id'), 'iep_ai_drafts', ['child_id'], unique=False)
    op.create_index(op.f('ix_iep_ai_drafts_parent_log_id'), 'iep_ai_drafts', ['parent_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iep_ai_drafts_parent_log_id'), table_name='iep_ai_drafts')
    op.drop_index(op.f('ix_iep_ai_drafts_child_id'), table_name='iep_ai_drafts')
    op.drop_table('iep_ai_drafts')
    # ### end Alembic commands ###
