"""init

Revision ID: f26419c854dc
Revises: 
Create Date: 2026-03-16 06:14:26.864846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26419c854dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_accounts_email'), 'cloud_accounts', ['email'], unique=True)
    op.create_table('abac_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abac_account_resource', 'abac_policies', ['account_id', 'resource'], unique=False)
    op.create_index('idx_abac_account_subject', 'abac_policies', ['account_id', 'subject'], unique=False)
    op.create_table('telemetry_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_account', 'telemetry_sync_logs', ['account_id'], unique=False)
    op.create_index('idx_telemetry_event_type', 'telemetry_sync_logs', ['event_type'], unique=False)
    op.create_index('idx_telemetry_synced_at', 'telemetry_sync_logs', ['synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_synced_at', table_name='telemetry_sync_logs')
    op.drop_index('idx_telemetry_event_type', table_name='telemetry_sync_logs')
    op.drop_index('idx_telemetry_account', table_name='telemetry_sync_logs')
    op.drop_table('telemetry_sync_logs')
    op.drop_index('idx_abac_account_subject', table_name='abac_policies')
    op.drop_index('idx_abac_account_resource', table_name='abac_policies')
    op.drop_table('abac_policies')
    op.drop_index(op.f('ix_cloud_accounts_email'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    # ### end Alembic commands ###
