"""add institution_status

Revision ID: f35fa30eba82
Revises: 39cd9c56f289
Create Date: 2026-03-23 19:33:11.442387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35fa30eba82'
down_revision: Union[str, Sequence[str], None] = '39cd9c56f289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('PENDING', 'APPROVED', name='institutionstatusenum')
    status_enum.create(op.get_bind(), checkfirst=True)
    
    # Check if column exists to avoid DuplicateColumnError
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('users')]
    if 'institution_status' not in columns:
        op.add_column('users', sa.Column('institution_status', status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institution_status')
    status_enum = sa.Enum('PENDING', 'APPROVED', name='institutionstatusenum')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
