import os
from pathlib import Path

# CONFIGURATION
OUTPUT_FILE = Path("knowledge_graph/ontology/SCHEMA_VISUALIZATION.md")

def generate_visualization():
    # We build the content as a list of lines to avoid "Triple Quote" Syntax Errors
    lines = []
    
    lines.append("# Knowledge Graph Schema Visualization (v2.0)")
    lines.append("")
    lines.append("**Status:** Reverse Engineered from `world_model_rescued.ttl`")
    lines.append("**Date:** 2026-01-29")
    lines.append("")
    lines.append("This diagram represents the *actual* structure of the data currently in the Knowledge Graph.")
    lines.append("")
    lines.append("## The Core Model")
    lines.append("")
    lines.append("```mermaid")
    lines.append("classDiagram")
    lines.append("    direction LR")
    lines.append("")
    lines.append("    %% --- CLASSES ---")
    lines.append("    class Word {")
    lines.append("        +string text")
    lines.append("        +string rdfs:label")
    lines.append("        +string pinyin")
    lines.append("        +float frequency")
    lines.append("        +int frequencyRank")
    lines.append("        +float ageOfAcquisition")
    lines.append("        +float concreteness")
    lines.append("        +int hskLevel")
    lines.append("        +string cefrLevel")
    lines.append("        +string partOfSpeech")
    lines.append("        +string learningTheme")
    lines.append("        +string learningLanguage")
    lines.append("    }")
    lines.append("")
    lines.append("    class Concept {")
    lines.append("        +string rdfs:label")
    lines.append("        +string rdfs:comment")
    lines.append("        +string wikidataId")
    lines.append("    }")
    lines.append("")
    lines.append("    class Character {")
    lines.append("        +string glyph")
    lines.append("        +string rdfs:label")
    lines.append("    }")
    lines.append("")
    lines.append("    class VisualImage {")
    lines.append("        +string imageFileName")
    lines.append("        +string imageFilePath")
    lines.append("        +string imageMimeType")
    lines.append("        +string sourcePackage")
    lines.append("    }")
    lines.append("")
    lines.append("    class GrammarPoint {")
    lines.append("        +string rdfs:label")
    lines.append("        +string structure")
    lines.append("        +string explanation")
    lines.append("        +string cefrLevel")
    lines.append("        +string category")
    lines.append("        +string sentenceType")
    lines.append("    }")
    lines.append("")
    lines.append("    class Sentence {")
    lines.append("        +string text")
    lines.append("        +string translationEN")
    lines.append("        +string pinyin")
    lines.append("    }")
    lines.append("")
    lines.append("    class PinyinNode {")
    lines.append("        %% Inferred from 'hasPinyin' linking to URIs")
    lines.append("        +string displayText")
    lines.append("    }")
    lines.append("")
    lines.append("    %% --- RELATIONSHIPS ---")
    lines.append("")
    lines.append("    %% Core Semantic Backbone")
    lines.append("    Word \"1\" --> \"1..*\" Concept : means")
    lines.append("    Concept \"1\" --> \"1..*\" Word : isExpressedBy")
    lines.append("")
    lines.append("    %% Literacy / Composition")
    lines.append("    Word \"1\" --> \"1..*\" Character : composedOf")
    lines.append("    Word \"1\" --> \"1..*\" Character : requiresPrerequisite")
    lines.append("")
    lines.append("    %% Visuals")
    lines.append("    Concept \"1\" --> \"0..*\" VisualImage : hasVisualization")
    lines.append("    VisualImage \"1\" --> \"1\" Concept : representsConcept")
    lines.append("")
    lines.append("    %% Grammar")
    lines.append("    GrammarPoint \"1\" --> \"0..*\" Sentence : hasExample")
    lines.append("    Sentence \"1\" --> \"1..*\" GrammarPoint : demonstratesGrammar")
    lines.append("    Sentence \"1\" --> \"1..*\" Word : containsWord")
    lines.append("")
    lines.append("    %% Pinyin Structure")
    lines.append("    Word \"1\" --> \"1\" PinyinNode : hasPinyin")
    lines.append("")
    lines.append("    %% Semantic Network")
    lines.append("    Concept --> Concept : isSynonymOf")
    lines.append("    Concept --> Concept : requiresPrerequisite")
    lines.append("```")
    lines.append("")
    lines.append("## Schema Health Analysis (Technical Debt)")
    lines.append("")
    lines.append("Based on the audit of the current data, the following inconsistencies must be resolved:")
    lines.append("")
    lines.append("### 1. Property Redundancy")
    lines.append("| Class | Issue | Recommendation |")
    lines.append("|---|---|---|")
    lines.append("| **Word** | Has both `text` and `rdfs:label`. | **Standardize on `rdfs:label`** for display text. |")
    lines.append("| **Sentence** | Has `demonstratesGrammar` and `illustratesGrammar`. | **Pick `illustratesGrammar`** as standard. |")
    lines.append("| **Concept** | Has `requiresPrerequisite` pointing to other Concepts. | Keep distinct from Word prerequisites. |")
    lines.append("")
    lines.append("### 2. The Pinyin Situation")
    lines.append("*   **Current State:** `hasPinyin` links to URIs, not literals.")
    lines.append("*   **Action:** Explicitly define `srs-kg:PinyinSyllable` in the ontology.")
    lines.append("")
    lines.append("### 3. Sentence Data Scarcity")
    lines.append("*   **Issue:** Audit shows very low counts for Sentence properties.")
    lines.append("*   **Action:** Verify Sentence deck population scripts.")
    lines.append("")
    
    # Join lines and write to file
    markdown_content = "\n".join(lines)

    # Ensure directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(markdown_content)

    print(f"✅ Generated Schema Visualization at: {OUTPUT_FILE}")
    print("👉 Open this file in your editor to view the Mermaid diagram.")

if __name__ == "__main__":
    generate_visualization()
